# Generated by Django 3.0.3 on 2020-10-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='long_number',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
