# Generated by Django 3.2.6 on 2021-08-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_personas_long_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
