# Generated by Django 3.0.3 on 2020-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
