# Generated by Django 3.0.3 on 2020-11-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0002_auto_20201121_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='name',
        ),
    ]
