# Generated by Django 3.0.3 on 2020-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0003_remove_devices_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
