# Generated by Django 3.0.3 on 2020-11-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0004_devices_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='active',
        ),
    ]
