# Generated by Django 3.0.3 on 2020-11-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0005_remove_devices_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
