# Generated by Django 3.0.3 on 2020-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0006_devices_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
