# Generated by Django 3.0.3 on 2020-11-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0007_accounts_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontrollers',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
