# Generated by Django 3.1.7 on 2021-07-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('smart_home', '0007_accounts_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller_devices',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microcontrollers',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.users'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='microcontroller_devices',
            name='microcontroller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.microcontrollers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
