# Generated by Django 3.0.3 on 2020-12-06 01:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0008_auto_20201125_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller_devices',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microcontroller_devices',
            name='microcontroller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.Microcontrollers'),
        ),
    ]
