# Generated by Django 3.2.6 on 2021-08-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0008_auto_20210726_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microcontroller_devices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
