# Generated by Django 3.2.6 on 2021-08-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0009_auto_20210824_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_users',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smart_home.accounts'),
        ),
        migrations.AlterField(
            model_name='microcontrollers_accounts',
            name='microcontroller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smart_home.microcontrollers'),
        ),
    ]
