# Generated by Django 3.1.7 on 2021-07-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbovespaCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'ibovespa_companies',
            },
        ),
        migrations.CreateModel(
            name='StockRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('value', models.FloatField()),
                ('growth', models.FloatField()),
                ('month', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserStocksTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=31)),
                ('code', models.CharField(max_length=31)),
                ('quantity', models.IntegerField()),
                ('value', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.users')),
            ],
            options={
                'db_table': 'user_stocks_transactions',
            },
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('quantity', models.IntegerField()),
                ('weighted_average_cost', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.users')),
            ],
            options={
                'db_table': 'user_stocks',
            },
        ),
        migrations.CreateModel(
            name='TransactionProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unitary_profit', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.userstockstransactions')),
            ],
            options={
                'db_table': 'transaction_profit',
            },
        ),
    ]
