# Generated by Django 3.1.7 on 2021-07-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IbovespaCompanies',
        ),
        migrations.DeleteModel(
            name='StockRecommendations',
        ),
    ]
