# Generated by Django 3.2.6 on 2021-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210726_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('value', models.FloatField()),
                ('reference_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_values',
            },
        ),
    ]
