# Generated by Django 3.2.6 on 2021-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210824_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvalues',
            name='reference_date',
            field=models.DateField(),
        ),
    ]
